name: Deploy Selected Branch to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'

permissions:
  contents: write

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.0.201'

      - name: Publish Blazor WebAssembly
        run: dotnet publish -c Release -o release --nologo

      - name: Change base-tag in index.html
        run: sed -i 's|<base href="/" />|<base href="/${{ env.REPO_NAME }}/${{ github.event.inputs.branch }}/" />|g' release/wwwroot/index.html

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
          target-folder: ${{ github.event.inputs.branch }}
